sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=xml:S5332
sonar.issue.ignore.multicriteria.e1.resourceKey=**/android/src/main/AndroidManifest.xml
sonar.issue.ignore.multicriteria.e2.ruleKey=xml:S6358
sonar.issue.ignore.multicriteria.e2.resourceKey=**/android/src/main/AndroidManifest.xml
