sonar.projectKey=Cap-go_capacitor-screen-recorder
sonar.organization=cap-go

sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=xml:S5332
sonar.issue.ignore.multicriteria.e1.resourceKey=Cap-go_capacitor-screen-recorder:android/src/main/AndroidManifest.xml
sonar.issue.ignore.multicriteria.e2.ruleKey=xml:S6358
sonar.issue.ignore.multicriteria.e2.resourceKey=Cap-go_capacitor-screen-recorder:android/src/main/AndroidManifest.xml
